# Welcome to Jekyll!

# Website settings
title: Wenbo's Website
description: suwenbo's blog,use Jekyll and github pages.
keywords: Jack,Jalpc,blog,Jekyll,github,gh-pages
baseurl:   # if you have suburl as homepage like '/homepage', please change it to '/homepage'
url: http://suwenbo1996520.github.io  # url should be changed to 'http://www.jack003.com/homepage' as before
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog  # url should be changed to '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: suwenbo  # Be used at blog posts' author.
  first_name: Wenbo  # Be used at index page about me section.
  last_name: Su  # Be used at index page about me section.
  cv:   # A online CV can be printed as PDF, leave blank if you don't have now
  email: xiaosu1996520@163.com  # Leave blank if you don't have now
  facebook_username: wenbo.su.54  # Leave blank if you don't have now
  github_username: suwenbo1996520  # Leave blank if you don't have now
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: Introduce myself will be here.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: suwenbo
  public_key: 

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not


# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
